### PR TITLE
Budget version of the metric

### PR DESCRIPTION
**Pull request by IlyaGusev**
Yapei, thank you for the great work!

This PR introduces a budget version of the metric. The main reason for the changes is to save money, as passing such a huge prompt for every sentence is just suboptimal.

Changes:
- Model selection in `obtain_response`
- v2 uses `gpt-4-turbo-preview` instead of `gpt-4`
- v2 uses batching: it processes several sentences with a single prompt.

Overall, the new version of the metric is around 20 times cheaper (x10 from batching and x2 from turbo).

### CODE REVIEW

**Comment by lilakk** [comment]
Hi Ilya,

Thank you so much for implementing this! The metric is definitely expensive to run and it would be great to give people the option of running a budget version. I'm wondering if you've compared the scores generated with this budget version with the original scores in https://github.com/lilakk/BooookScore/tree/main/gpt4_annotations? How much different are they?

**Comment by IlyaGusev** [comment]
I've evaluated 3 sets of summaries. One v2 run on 100 summaries costs around 25$. Here are the results:

| Model | v1 score | v2 score |
|-------|----------|----------|
| GPT-4 2048 hierarchical | 89.4 | 90.8 |
| ChatGPT 2048 hierarchical | 84.5 | 88.2 |
| ChatGPT 2048 incremental | 67.7 | 77.9 |

So, v2 scores are inflated, but the order of models remains the same.

**Comment by lilakk** [comment]
That seems great, thanks again for doing this!

**Comment by IlyaGusev** [comment]
Thank you!

I've fixed the prompt a bit in [7f17e34](https://github.com/lilakk/BooookScore/pull/2/commits/7f17e341fefb24fbf90ed3c8a0e2fcbde95c3285) (already merged) and re-calculated the scores. Now, they are even closer to the original ones:
|Model | v1 score |v2 score|
|-|-|-|
|GPT-4 2048 hierarchical | 89.4 | 90.0 |
| ChatGPT 2048 hierarchical | 84.5 | 87.0 |
| ChatGPT 2048 incremental | 67.7 | 76.6 |

**Comment by lilakk** [comment]
That's awesome, thanks!

**Pull request merged**
